# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
development:
  a_periodic_job:
    class: SendNotificationJob
    queue: background
    schedule: every 5 seconds
  b_periodic_job:
    class: DeleteNotificationJob
    queue: cleanup_queue
    schedule: every 20 seconds
  c_periodic_job:
    class: DeleteFinishedSolidQueueJob
    queue: cleanup_queue
    schedule: at 2am every day 